[package]
name = "evolution_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rand_chacha = "0.3"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
